name: Android CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Install Android SDK
        run: sdkmanager "platform-tools" "platforms;android-34" "emulator" "system-images;android-34;default;x86_64"

      - name: Accept SDK Licenses
        run: yes | sdkmanager --licenses

      - name: Cache Gradle Packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{runner.os}}-gradle-${{hashFiles('**/*.gradle*', '**/gradle-wrapper.properties')}}
          restore-keys: |
            ${{runner.os}}-gradle-      

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create LOCAL_PROPERTIES
        run: echo '${{ secrets.LOCAL_PROPERTIES }}' > ./local.properties

      - name: Clean Managed Devices
        run: ./gradlew cleanManagedDevices --unused-only

      - name: Generate Baseline Profile
        run: ./gradlew :app:generateBaselineProfile

      - name: Run ktlint
        run: ./gradlew ktlintCheck

      - name: Build with Gradle
        run: ./gradlew build

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Generate baseline profiles"
          title: "Generate baseline profiles"
          delete-branch: true
          branch: actions/baseline-profiles

      - name: Go-Socket Android CI Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: ${{ success() }}
        with:
          title: ✅ Go-Socket-Android-CI 성공! ✅
          webhook: ${{ secrets.GO_SOCKET_DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          image: ${{ secrets.SUCCESS_IMAGE }}
          color: 00FF00
          url: "https://github.com/sarisia/actions-status-discord"
          username: Go-Socket CI 봇

      - name: Go-Socket Android CI Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: ${{ failure() }}
        with:
          title: ❗️ Go-Socket-Android-CI 실패! ❗️
          webhook: ${{ secrets.GO_SOCKET_DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          image: ${{ secrets.FAILED_IMAGE }}
          color: 00FF00
          url: "https://github.com/sarisia/actions-status-discord"
          username: Go-Socket CI 봇